
simulation_name: "gotthard_asta_short"

robot_name: gotthard  
kill_after: 6000      

pkg_config_storage: common # relative paths to config files w.r.t this package
repetitions:
- {track_name: asta_zero_short.sdf, autonomous_stack: }

# stop if we go off the track
res:
  checks:
    is_in_track: false

# Launch files for autonomous missions
launch_file:
  rosbag_record: 

