# Experiment configuration

t_activate: 5.0
t_final: 500.0
scenario_id: 6 # 1: pop-up, 2: reduced mu turn, 3: racing 4: local min test 5: pp-test 6: tamp test

# pop-up obstacle config
obstacle_config: no_popup
obstacle_wiggleroom: 1.0

# TUNING/PREP

# initial test static friction static speed (asta_zero_long)
#s_begin_mu_segments:  [0.0]
#mu_segment_values:  [0.8]
#s_begin_vxref_segments: [0.0, 600.0]
#vxref_segment_values: [10.0, 5.0]

# long ctrl tuning (asta_zero_long)
#s_begin_vxref_segments: [0.0, 310.0, 400.0, 550.0]
#vxref_segment_values: [10.0, 10.0, 15.0, 3.0]
#s_begin_mu_segments:  [0.0]
#mu_segment_values:  [0.8]

# EXPERIMENTS
# high friction run (asta_zero_short)
#s_begin_mu_segments:  [0.0]
#mu_segment_values:  [0.8]
#s_begin_vxref_segments: [0.0, 315.0, 600.0]
#vxref_segment_values: [15.0, 10.0, 5.0]

# low friction run (asta_zero_long)
s_begin_mu_segments:  [0.0, 230.0, 330.0]
mu_segment_values:  [0.8, 0.4, 0.8] 
s_begin_vxref_segments: [0.0, 315.0, 600.0]
#s_begin_vxref_segments: [0.0]
vxref_segment_values: [1.0, 3.0, 3.5]
#vxref_segment_values: [3.0]

# low friction run (asta_zero_short)
#s_begin_mu_segments:  [0.0, 235.0, 295.0]
#mu_segment_values:  [0.8, 0.4, 0.8]
#s_begin_vxref_segments: [0.0, 300.0, 500.0]
#vxref_segment_values: [8.0, 8.0, 5.0]

# sim pause (empty if no pauses or real exp)
s_sim_pause:  []

# dref
cc_dref: 0

# pcs refs
#pcs_vxref: 1.0
#pcs_dref: -1

### saarti algorithm config		

# Reference mode, 
# 0: minimize s
# 1: cc @ cc_vxref
# 2: maximize s
ref_mode: 1

# Algorithm mode, 
# 0: RTI
# 1: SAA-RTI 
sampling_augmentation: 1
Nd_rollout: 10 # multiples of 32 to maximize gpu utilization
Nvx_rollout: 15
vxub_rollout: 3.6

# Traction adaptation 
# 0: nominal value of mu from param mu_nominal and static tire force constraints (no pitch dynamics), static Cr
# 1: takes mu estimate from pathlocal struct and computes normal forces from pitch dynamics, Cr from mu and Fz
traction_adaptive: 1
mu_nominal: 0.8 # used when traction_adaptive = 0 and as initial mu est

# friction estimation mode (for exp1)
# 0: ground truth (same as camera only GT)
# 1: local only (GT)
# 2: local only (with noise)
# 3: camera only (with noice)
# 4: merged local + camera (GP)
mu_est_mode: 0
do_live_plot_mu_est: 0

# conservative or agressive (for exp2) 
# -1: conservative  
# 0: neutral
# 1: aggressive
conservativeness_level: -1


# Force utilization factor
#Ff_util: 0.8 # final tests
#Fr_util: 0.8
#Ff_util: 0.5 # initial tuning runs
#Fr_util: 0.5
Ff_util: 0.9 # sim
Fr_util: 0.9
# optimization config
Wx:  [1.0, 50.0, 0.1, 0.1, 50.0, 0.0001]
WNx: [1.0, 50.0, 0.1, 0.1, 50.0, 0.0001]
Wu: [1.0, 1.0, 1.0]
Wslack: 100000000

# rollout controller config
K: [0.000, 59.865, 120.107, 0.455, -0.000, 22.613,
 0.611, -0.000, -0.000, -0.000, 6.387, -0.000,
 0.611, -0.000, -0.000, -0.000, 6.387, -0.000]



